package com.model;
// Generated 11-feb-2017 21:28:21 by Hibernate Tools 4.3.5.Final

/**
 * Apoint generated by hbm2java
 */
public class Apoint implements java.io.Serializable {

	private Long id;
	private Travel travel;
	private String latitude;
	private String longuitude;

	public Apoint() {
	}

	public Apoint(Travel travel) {
		this.travel = travel;
	}

	public Apoint(Travel travel, String latitude, String longuitude) {
		this.travel = travel;
		this.latitude = latitude;
		this.longuitude = longuitude;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Travel getTravel() {
		return this.travel;
	}

	public void setTravel(Travel travel) {
		this.travel = travel;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public String getLonguitude() {
		return this.longuitude;
	}

	public void setLonguitude(String longuitude) {
		this.longuitude = longuitude;
	}

}
