package com.model;
// Generated 11-feb-2017 21:28:21 by Hibernate Tools 4.3.5.Final

/**
 * Photo generated by hbm2java
 */
public class Photo implements java.io.Serializable {

	private Long id;
	private Route route;
	private String name;
	private String path;

	public Photo() {
	}

	public Photo(Route route) {
		this.route = route;
	}

	public Photo(Route route, String name, String path) {
		this.route = route;
		this.name = name;
		this.path = path;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Route getRoute() {
		return this.route;
	}

	public void setRoute(Route route) {
		this.route = route;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

}
