package com.model;
// Generated 11-feb-2017 21:28:21 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.OneToOne;

/**
 * Route generated by hbm2java
 */
public class Route implements java.io.Serializable {

	private Long id;
	private Travel travel;
	private User user;
	@OneToOne
	private Activity activity;
	private Date date;
	private String description;
	@Enumerated(value = EnumType.STRING)
	private Difficulty difficulty;
	private float distance;
	private boolean isCircular;
	private boolean isPublic;
	private String name;
	private Date time;
	private Set<Photo> photos = new HashSet<Photo>(0);
	private Set<UserRoute> userRoutes = new HashSet<UserRoute>(0);
	private Set<Routescore> routescores = new HashSet<Routescore>(0);

	public Route() {
		this.activity = new Activity();
	}

	public Route(Travel travel, float distance, boolean isCircular, boolean isPublic) {
		this.travel = travel;
		this.distance = distance;
		this.isCircular = isCircular;
		this.isPublic = isPublic;
	}

	public Route(Travel travel, User user, Activity activity, Date date, String description, Difficulty difficulty,
			float distance, boolean isCircular, boolean isPublic, String name, Date time, Set<Photo> photos,
			Set<UserRoute> userRoutes, Set<Routescore> routescores) {
		this.travel = travel;
		this.user = user;
		this.activity = activity;
		this.date = date;
		this.description = description;
		this.difficulty = difficulty;
		this.distance = distance;
		this.isCircular = isCircular;
		this.isPublic = isPublic;
		this.name = name;
		this.time = time;
		this.photos = photos;
		this.userRoutes = userRoutes;
		this.routescores = routescores;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Travel getTravel() {
		return this.travel;
	}

	public void setTravel(Travel travel) {
		this.travel = travel;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Activity getActivity() {
		return this.activity;
	}

	public void setActivity(Activity activity) {
		this.activity = activity;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Difficulty getDifficulty() {
		return this.difficulty;
	}

	public void setDifficulty(Difficulty difficulty) {
		this.difficulty = difficulty;
	}

	public float getDistance() {
		return this.distance;
	}

	public void setDistance(float distance) {
		this.distance = distance;
	}

	public boolean isIsCircular() {
		return this.isCircular;
	}

	public void setIsCircular(boolean isCircular) {
		this.isCircular = isCircular;
	}

	public boolean isIsPublic() {
		return this.isPublic;
	}

	public void setIsPublic(boolean isPublic) {
		this.isPublic = isPublic;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public Set<Photo> getPhotos() {
		return this.photos;
	}

	public void setPhotos(Set<Photo> photos) {
		this.photos = photos;
	}

	public Set<UserRoute> getUserRoutes() {
		return this.userRoutes;
	}

	public void setUserRoutes(Set<UserRoute> userRoutes) {
		this.userRoutes = userRoutes;
	}

	public Set<Routescore> getRoutescores() {
		return this.routescores;
	}

	public void setRoutescores(Set<Routescore> routescores) {
		this.routescores = routescores;
	}

	public String getPrivacidad() {
		if (isPublic) {
			return "Pública";
		} else {
			return "Privada";
		}
	}

	public String getFormato() {
		if (isCircular) {
			return "Circuito";
		} else {
			return "Sólo ida";
		}
	}

}
