package com.model;
// Generated 11-feb-2017 21:28:21 by Hibernate Tools 4.3.5.Final

/**
 * Routescore generated by hbm2java
 */
public class Routescore implements java.io.Serializable {

	private Long id;
	private Route route;
	private User user;
	private int score;

	public Routescore() {
	}

	public Routescore(Route route, User user, int score) {
		this.route = route;
		this.user = user;
		this.score = score;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Route getRoute() {
		return this.route;
	}

	public void setRoute(Route route) {
		this.route = route;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public int getScore() {
		return this.score;
	}

	public void setScore(int score) {
		this.score = score;
	}

}
