package com.model;
// Generated 11-feb-2017 21:28:21 by Hibernate Tools 4.3.5.Final

/**
 * UserRoute generated by hbm2java
 */
public class UserRoute implements java.io.Serializable {

	private UserRouteId id;
	private Route route;
	private User user;

	public UserRoute() {
	}

	public UserRoute(UserRouteId id, Route route, User user) {
		this.id = id;
		this.route = route;
		this.user = user;
	}

	public UserRouteId getId() {
		return this.id;
	}

	public void setId(UserRouteId id) {
		this.id = id;
	}

	public Route getRoute() {
		return this.route;
	}

	public void setRoute(Route route) {
		this.route = route;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
