package com.model;
// Generated 11-feb-2017 21:28:21 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Long id;
	private boolean active;
	private String address;
	private Date birthdate;
	private int dni;
	private String email;
	private String lastName;
	private String name;
	private String password;
	private String roll;
	private String sex;
	private String userName;
	private Set<Routescore> routescores = new HashSet<Routescore>(0);
	private Set<Route> routes = new HashSet<Route>(0);
	private Set<UserRoute> userRoutes = new HashSet<UserRoute>(0);

	public User() {
	}

	public User(User us) {
		this.active = us.getActive();
		this.address = us.getAddress();
		this.birthdate = us.getBirthdate();
		this.dni = us.getDni();
		this.email = us.getEmail();
		this.lastName = us.getLastName();
		this.name = us.getName();
		this.password = us.getPassword();
		this.roll = us.getRoll();
		this.sex = us.getSex();
		this.userName = us.getUserName();
	}

	public User(boolean active, int dni) {
		this.active = active;
		this.dni = dni;
	}

	public User(boolean active, String address, Date birthdate, int dni, String email, String lastName, String name,
			String password, String roll, String sex, String userName, Set<Routescore> routescores, Set<Route> routes,
			Set<UserRoute> userRoutes) {
		this.active = active;
		this.address = address;
		this.birthdate = birthdate;
		this.dni = dni;
		this.email = email;
		this.lastName = lastName;
		this.name = name;
		this.password = password;
		this.roll = roll;
		this.sex = sex;
		this.userName = userName;
		this.routescores = routescores;
		this.routes = routes;
		this.userRoutes = userRoutes;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Date getBirthdate() {
		return this.birthdate;
	}

	public void setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}

	public int getDni() {
		return this.dni;
	}

	public void setDni(int dni) {
		this.dni = dni;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRoll() {
		return this.roll;
	}

	public void setRoll(String roll) {
		this.roll = roll;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Set<Routescore> getRoutescores() {
		return this.routescores;
	}

	public void setRoutescores(Set<Routescore> routescores) {
		this.routescores = routescores;
	}

	public Set<Route> getRoutes() {
		return this.routes;
	}

	public void setRoutes(Set<Route> routes) {
		this.routes = routes;
	}

	public Set<UserRoute> getUserRoutes() {
		return this.userRoutes;
	}

	public void setUserRoutes(Set<UserRoute> userRoutes) {
		this.userRoutes = userRoutes;
	}

	public String getEstado() {
		if (active) {
			return "Habilitado";
		} else {
			return "Deshabilitado";
		}
	}

	public boolean getActive() {
		return this.active;
	}

	public boolean isAdmin() {
		return (this.getRoll().equals("Admin"));

	}

}
