package com.model;
// Generated 11-feb-2017 21:28:21 by Hibernate Tools 4.3.5.Final

/**
 * UserRouteId generated by hbm2java
 */
public class UserRouteId implements java.io.Serializable {

	private long userId;
	private long traveledRoutesId;

	public UserRouteId() {
	}

	public UserRouteId(long userId, long traveledRoutesId) {
		this.userId = userId;
		this.traveledRoutesId = traveledRoutesId;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public long getTraveledRoutesId() {
		return this.traveledRoutesId;
	}

	public void setTraveledRoutesId(long traveledRoutesId) {
		this.traveledRoutesId = traveledRoutesId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserRouteId))
			return false;
		UserRouteId castOther = (UserRouteId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getTraveledRoutesId() == castOther.getTraveledRoutesId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUserId();
		result = 37 * result + (int) this.getTraveledRoutesId();
		return result;
	}

}
